### ISSUE TITLE
PolygonNotFoundException

### ISSUE THREAD

**Issue by haffadan** [voidp-nt-r/tomtom-compose#2]
If  a polygon is on map when navigating to other screen a  FATAL EXCEPTION: main
com.tomtom.sdk.map.display.polygon.PolygonNotFoundException: Cannot find Polygon: 277
when not using a polygon, navigation works fine.

This dosen't happen to Circle, Marker or Polyline.

**Comment by voidp-nt-r** [comment]
Hi, thanks so much for contributing!

It seems to have been resolved. The error was occurring because I didn't realize that I implemented the “onCleared” function on the polygons, so the code wants to delete the polygon twice, causing the exception.
